# MLIP-HOT: Formation energy only
# Compatible with scripts/MLIP_HOT.py

task: form

form:
  input: example/example_result/example_data.csv
  database_elements: example/terminal_elements_mp.csv
  output: example/example_result/example_data_dft.csv
  composition_column_input: optimized_formula
  composition_column_elements: composition
  energy_column_input: Energy (eV/atom)
  energy_column_elements: Energy (eV/atom)
  out_column: Formation Energy (eV/atom)
