# MLIP-HOT: Hull distance only
# Compatible with scripts/MLIP_HOT.py

task: hull

hull:
  database_candidate: example/example_result/example_data_dft.csv
  database_convex: example/example_result/convex_hull_compounds_mp.csv
  output: example/example_result/example_data_result_mp.csv
  formula_column_candidate: optimized_formula
  formula_column_convex: optimized_formula
  formE_column_candidate: Formation Energy (eV/atom)
  formE_column_convex: Formation Energy (eV/atom)
  out_column: Hull Distance (eV/atom)
  # mpi: { enable: true, nproc: 4 }
